### ISSUE TITLE
I do not understand

### ISSUE THREAD

**Issue by BlooketHackerx** [ThatFruedDued/blooket-utility-ploader#1]
Is there a way to use this in a bookmarklet or do we have to download the ZIP file?

**Comment by ThatFruedDued** [comment]
Hi, there is a live beta running at https://blooket-utility.herokuapp.com. Go to https://blooket-utility.herokuapp.com/conf to add injectables and configure the utility.

**Comment by BlooketHackerx** [comment]
Okay so I hate to be a pain. But I did go to the link for the configuration and when I tried to add an injectable made by glixxy it told me it was invalid. Is there something I am missing? I must be dumb in your point of view since you are so good at this. Anyways let me know.

**Comment by ThatFruedDued** [comment]
Hi, sorry, but the glixzzy injectable was created for the old version of the Blooket Utility. Please try using some of the new ones (the ones with folders and `injectable.json` files are made for the new version!)

**Comment by BlooketHackerx** [comment]
I tried multiple and still cannot seem to figure it out, so I will stop bothering you unless you know of one that works, as I do not want to waste your time but thank you so much for trying, I guess I am just too dumb to understand this stuff. Anyways let me know if you know of an injectable that works because every single one I tried does not. Thanks.

**Comment by ThatFruedDued** [comment]
Sorry for not being more clear, you must link the `injectable.json` file. Try this URL: https://thatfrueddued.github.io/blooket-utility-injectables/injectables/customMaps/injectable.json

**Comment by BlooketHackerx** [comment]
Oh. It worked. Thank you so much and so sorry for wasting your time. I really REALLY appreciate it!!

**Comment by ThatFruedDued** [comment]
No problem!
